# Generated by Django 5.2.14 on 2026-05-15 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='Год смерти')),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место рождения')),
                ('biography', models.TextField(verbose_name='Биография')),
                ('image', models.ImageField(blank=True, null=True, upload_to='figures/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Историческое лицо',
                'verbose_name_plural': 'Исторические лица',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='historical_figures.historicalfigure')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='Год смерти')),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место рождения')),
                ('biography', models.TextField(verbose_name='Биография')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Предложил')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
    ]
